### PR TITLE
Fix strings, update translations

### PR DESCRIPTION
**Pull request by tosky**
Fix few typos (spotted by lintian tool); fix few typos for Spanish translations (originally contributed for the Debian packaging); update translation templates and po files; update Italian translation.

### CODE REVIEW

**Comment by tosky** [comment]
If this is merged, I would suggest a call for translations (asking the former translators) and then maybe release a stable 2.10 (final for kdelibs4), then move to the Frameworks port :)

**Comment by gl-bars** [comment]
Thanks!
Initial Frameworks port (v2.49-alpha) is 99% ready, after it's finished I plan to start working on kde4 / 2.11 release (not sure if it will leave the beta stage...)

**Comment by tosky** [comment]
Thanks you!
But if you consider the kdelibs4 version as still beta, why not release another version 2.11 now, and  then call the next one 2.12, etc? Right now, if you see the debian package, I need to use a quite long identifier as version number...
And the call for translators is needed for both branches anyway :)

**Comment by tosky** [comment]
(and please merge master into kde5port)

**Comment by gl-bars** [comment]
Because it is not ready yet. Besides some old tickets from bugs.kde.org, a major thing to be fixed is libgit not controllable from GUI yet.
In my opinion the stable release for KDE 4 should remain v2.10 + probably some patches (like 43890d6242a1f6b5c285633c4b69bd3bd9d8a03e).

**Pull request merged**
